spring:
  application:
    name: taskflow-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email